### ISSUE TITLE
Error when completing: using List as String

### ISSUE THREAD

**Issue by mgraham** [hauleth/pivotaltracker.vim#1]
Hey - I'm getting an error when attempting to run completion:
```
Error detected while processing function pivotaltracker#stories[12]..pivotaltracker#build_cache[1]..<SNR>275_fetch:
line   56:
E730: using List as a String
Error detected while processing function pivotaltracker#stories[12]..pivotaltracker#build_cache[1]..<SNR>275_fetch[56]..<SNR>275_parse:
line    1:
E712: Argument of map() must be a List or Dictionary
```

Here's my config (stripped of almost everything):
```
let g:pivotaltracker_token = "abcdefabcdefabcdefabcdefabcdefab"
let g:pivotaltracker_id = "555111"
let g:pivotaltracker_name = "myfullusername"
let g:pivotaltracker_filter = ""
```

Any ideas?

**Comment by hauleth** [comment]
I am not handling errors properly right now. So if there is any error there will be such message. I have encountered this myself a few times (due to some API errors that I am still investigating) so this is quite important to me also.

**Comment by mgraham** [comment]
I did some digging, and it looks like my problem is that 
```
    if exists('*async#job#start')
```

returns false.  Not sure what that means.

(Edit: I'm on I'm on vim 8.0.525 (130) (MacVim), by the way)

**Comment by hauleth** [comment]
It will return false when there is no [`async`](https://github.com/prabirshrestha/async.vim) library installed or loaded, so it fallbacks to using synchronous call, it shouldn't be a problem though.

I will look through and try to fix that soon.

**Comment by mgraham** [comment]
Thank you!  I think it's because I'm on vim8, and not neovim.  Might be time for me to finally switch :)

**Comment by hauleth** [comment]
@mgraham the plugin should work in Vim8 as well.
